baseURL = 'https://blog.sanidhya.tech/'
languageCode = 'en-us'
title = 'Sanidhya Soni - Security Blog'
theme = 'mana'

[outputs]
  home = ["HTML", "JSON"]  # Enable search functionality

[pagination]
  pageSize = 10

[params]
  description = "Security research, CTF writeups, and red teaming insights by Sanidhya Soni"
  favicon = "/favicon/favicon.ico"
  footerText = "Â© 2026 Sanidhya Soni. All rights reserved."
  heroTitleLine1 = "Security"
  heroTitleLine2 = "Research & CTFs"
  
  [params.avatar]
    url = "/images/avatar.jpg"
  
  [params.social]
    github = "https://github.com/yourusername"
    linkedin = "https://www.linkedin.com/in/sanidhyasonii"
    email = "sanidhyasonii@proton.me"

[[menus.main]]
  name = 'Home'
  pageRef = '/'
  weight = 10

[[menus.main]]
  name = 'Posts'
  pageRef = '/posts'
  weight = 20

[[menus.main]]
  name = 'Tags'
  pageRef = '/tags'
  weight = 30

[[menus.main]]
  name = 'About'
  url = '/about/'
  weight = 40

[[menus.main]]
  name = 'Portfolio'
  url = 'https://sanidhya.tech'
  weight = 50

[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true
        title = true
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 6
    ordered = false
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    noClasses = false
    style = "catppuccin-macchiato"

[params.codeHighlight]
  darkTheme = "catppuccin-macchiato"
  lightTheme = "catppuccin-frappe"
